#!/bin/bash

# Run this from the root of the project
version=$(grep version pyproject.toml | sed -E -n 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
docker build -t chadbowman0/litterkicker:$version -t chadbowman0/litterkicker:latest -f docker/Dockerfile .
