#!/bin/bash

# Run this from the root of the project
version=$(grep version pyproject.toml | sed -E -n 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
docker push chadbowman0/litterkicker:$version && docker push chadbowman0/litterkicker:latest
